### ISSUE TITLE
pystemon does not work

### ISSUE THREAD

**Issue by Gr3gbug** [cvandeplas/pystemon#107]
Hi, i'm trying to use pystemon, i downloaded it and i run it with the default .yaml config but i get this error, any suggestions about that ?

`[2020-10-23 11:05:00,603] Retry client=0/5, server=33/100 for http://pastebin.gr/paste.php?download&id=1
[2020-10-23 11:05:00,695] Failed to download the page because of other HTTPlib error proxy error: http://pastebin.gr/paste.php?download&id=1
[2020-10-23 11:05:00,696] Traceback (most recent call last):
  File "./pystemon.py", line 993, in __download_url__
    res = __parse_http__(url, session, random_proxy)
  File "./pystemon.py", line 956, in __parse_http__
    response.raise_for_status()
  File "/home/parallels/Develop/pystemon/venv/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://pastebin.gr/paste.php?download&id=1
`

Thank you in advance!

**Comment by cvandeplas** [comment]
This seems to be an issue with your proxy that is refusing connections.

**Comment by cvandeplas** [comment]
closing due to no feedback
